In [1]:
!pip3 install numpy

     |████████████████████████████████| 15.4 MB 19 kB/s eta 0:00:016


In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [8]:
#Q1:生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。

In [14]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
np.arange(0, 21, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
np.linspace(0, 20, num=21, endpoint=True)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [15]:
#Q2:呈上題，將以上數列取出偶數。

In [17]:
a[2:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
#Q3:呈 1 題，將數列取出 3 的倍數。

In [20]:
a[3:21:3]

array([ 3,  6,  9, 12, 15, 18])